version: 2.1
commands:
  build:
    description: "Perform build steps"
    parameters:
      base_dir:
        type: string
        default: "Hello World"
        
    steps:
      - restore_cache:
          key: << parameters.base_dir >>-{{ checksum "<< parameters.base_dir >>/build.gradle" }}
      - run: 
          name: Building and UnitTesting
          command: cd << parameters.base_dir >> && ./gradlew build 
      - save_cache: 
                paths:
                  - .gradle
                key: << parameters.base_dir >>-{{ checksum "<< parameters.base_dir >>/build.gradle" }}
jobs: 
  all: 
    working_directory: ~/poc-space

    docker: 
      - image: circleci/openjdk:11-jdk-browsers

    steps: 
      - checkout
      - build:
          base_dir: "reactive-demo"
      - build:
          base_dir: "spring-tx-demo"

workflows:
  version: 2
  all:
    jobs:
      - all