version: 2.1
jobs: 
  reactive_demo: 
    working_directory: ~/poc-space

    docker: 
      - image: circleci/openjdk:11-jdk-browsers

    steps: 
      - checkout
      - restore_cache:
          key: reactive-demo-{{ checksum "reactive-demo/build.gradle" }}
      - run: cd reactive-demo && ./gradlew build
      - save_cache: 
          paths:
            - .gradle
          key: reactive-demo-{{ checksum "reactive-demo/build.gradle" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/poc-space/reactive-demo/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/poc-space/reactive-demo/test-results/junit/ \;
          when: always
      - run:
          name: Codacy Coverage
          command: | 
            curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
            chmod +x codacy-coverage-reporter
            ./codacy-coverage-reporter report -l Java -r reactive-demo/build/reports/jacoco/test/jacocoTestReport.xml
      - store_test_results: 
          path: ~/poc-space/reactive-demo/test-results
      - store_artifacts: 
          path: ~/poc-space/reactive-demo/test-results/junit
      - store_artifacts: 
          path: reactive-demo/build/jacoco
      - store_artifacts: 
          path: reactive-demo/build/reports

workflows:
  version: 2
  all:
    jobs:
      - reactive_demo