version: 2.1
jobs: 
  reactive_demo: 
    working_directory: ~/poc-space/reactive-demo

    docker: 
      - image: circleci/openjdk:11-jdk-browsers

    steps: 
      - checkout
      - restore_cache:
          key: reactive-demo-{{ checksum "reactive-demo/build.gradle" }}
      - run: cd reactive-demo && ./gradlew build
      - save_cache: 
          paths:
            - ~/.m2
            - .gradle
          key: reactive-demo-{{ checksum "reactive-demo/build.gradle" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/poc-space/reactive-demo/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/poc-space/reactive-demo/test-results/junit/ \;
          when: always
      - store_test_results: 
          path: ~/poc-space/reactive-demo/test-results
      - store_artifacts: 
          path: ~/poc-space/reactive-demo/test-results/junit
      - store_artifacts: 
          path: reactive-demo/build/jacoco
          destination: ~/poc-space/reactive-demo/jacoco
      - store_artifacts: 
          path: reactive-demo/build/reports
          destination: ~/poc-space/reactive-demo/reports

workflows:
  version: 2
  all:
    jobs:
      - reactive_demo