version: 2.1
jobs: 
  reactive_demo: 
    working_directory: ~/reactive-demo

    docker: 
      - image: circleci/openjdk:8-jdk-browsers

    steps: 
      - checkout
      - restore_cache:
          key: reactive-demo-{{ checksum "build.gradle" }}
      - run: cd reactive-demo && ./gradlew build
      - save_cache: 
          paths:
            - ~/.m2
            - .gradle
          key: prady-hello-{{ checksum "build.gradle" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            cd reactive-demo && find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results: 
          path: ~/test-results
      - store_artifacts: 
          path: ~/test-results/junit
      - store_artifacts: 
          path: build

workflows:
  version: 2
  all:
    jobs:
      - reactive_demo